import { Inter } from "next/font/google";
import "./globals.css";
import SessionProviderAuth from "./components/sessionProviderAuth";
import SideBarMain from "./util/sidebarMain";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* wrapping body in SessionProviderAuth will allow session to be available in all the pages */}
      <SessionProviderAuth>
        <body className={`${inter.className} flex `}>
          <SideBarMain/>
          {children}</body>
          {/* <div>Vishwakarma</div> */}
      </SessionProviderAuth>
    </html>
  );
}
